---
version: '3.1'
services:
  web-proxy:
    image: venkynagidi/two:mydockerimage
    ports:
      - "3000:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  networks:
    default:
      external:
        name: nginx-proxy  
      
